[package]
name = "host_primitives"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
qos_core = { workspace = true}
qos_crypto = { workspace = true } # sha_256 for payment_marker hashing

tonic = { version = "0.10", default-features = false }
prost = { version = "0.12", features = [
  "prost-derive",
  "std",
], default-features = false }
borsh = { version = "1.0", features = [
  "std",
  "derive",
], default-features = false }
generated = { path = "../generated", features = ["serde_derive"] }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
