[package]
name = "visualsign"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
description = "Visualsign package defines the structures helper methods to create VisualSign payloads for Anchorage's Open Source VisualSign"
# Inherit from root
license.workspace = true
repository.workspace = true

[dependencies]
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
pretty_assertions = "1.4.1"
thiserror = "2.0.12"
# the most minimal regex import so that I can do number validation
regex = { version = "1.11.1", default-features = false, features = ["std"] }
sha2 = "0.10"
hex = { workspace = true }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tracing = { workspace = true }
generated = { path = "../generated" }

[dev-dependencies]
base64 = "0.22.1"

[features]
diagnostics = []

[lints]
workspace = true
